import { motion, useScroll, useTransform } from "framer-motion";
import { useRef } from "react";
import { Link } from "@tanstack/react-router";
import aiCulinary from "@/assets/portfolio/aiculinary.jpg";
import examGrading from "@/assets/portfolio/exam.png";
import fertilizer from "@/assets/portfolio/fertilizer.png";
import timeSeries from "@/assets/portfolio/timeseries.png";
import speaker from "@/assets/portfolio/speaker.png";
import { EASE, MaskReveal } from "./motion-primitives";

export interface Project {
  slug: string;
  index: string;
  title: string;
  stack: string;
  year: string;
  role: string;
  description: string;
  highlight?: string;
  image: string;
  href?: string;
  github?: string;
  context?: string;
  approach?: string;
  reflection?: string;
}

export const projects: Project[] = [
  {
    slug: "ai-culinary-companion",
    index: "01",
    title: "AI Culinary Companion",
    stack: "React · TypeScript · Tailwind · Gemini 2.5-flash",
    year: "2025",
    role: "Product & GenAI",
    description:
      "An AI-powered Vietnamese recipe finder backed by Google Gemini 2.5-flash for intelligent recipe generation and smart search.",
    highlight: "101+ Vietnamese recipes",
    image: aiCulinary,
    href: "https://ai-culinary-companion-seven.vercel.app/",
    github: "https://github.com/lpsangg/AI-Culinary-Companion",
    context:
      "A modern web application designed to help users search, filter, and discover traditional Vietnamese recipes. Traditional recipe finders are often static and hard to navigate, but this project combines a rich dataset of 101+ Vietnamese dishes with an AI culinary assistant powered by Google Gemini 2.5-flash to generate custom, structured recipes on the fly.",
    approach:
      "Built using React 19, TypeScript, and Vite for a highly responsive, modern frontend. The AI assistant leverages the official @google/generative-ai SDK, configured with structured output formatting to guarantee that the recipes generated by Gemini always return valid JSON matching our application's design system. Used Tailwind CSS for a responsive grid layout, supporting detailed filters such as cooking time, difficulty levels, dietary restrictions, and portion sizes.",
    reflection:
      "Integrating LLMs in user-facing applications requires strict output schema validation. Working with Gemini's structured output mode taught me how to constrain LLM responses to prevent UI breakage while delivering personalized recipes in real-time.",
  },
  {
    slug: "automatic-exam-grading",
    index: "02",
    title: "Automatic Exam Grading",
    stack: "Next.js · FastAPI · Ollama qwen2.5vl:3b · OpenCV",
    year: "2025",
    role: "Vision-Language AI",
    description:
      "A full-stack Vision-Language system that automates exam grading. The model reads handwritten answers and scores them against a rubric.",
    highlight: "End-to-end VLM pipeline",
    image: examGrading,
    href: "https://youtu.be/ActhTB7nxiQ",
    github: "https://github.com/lpsangg/exam-grading-system",
    context:
      "Multiple-choice exams are quick to score but manual grading sheets and standard optical mark readers are expensive and inflexible. This system provides a web-based automated exam grading solution using computer vision and local vision-language models (VLMs) to read, score, and manage exam sheets from camera photos.",
    approach:
      "Built the frontend using Next.js and TailwindCSS, backed by a FastAPI backend. The image preprocessing pipeline is written in Python using OpenCV to perform perspective correction, image alignment, and bubble-sheet detection. For complex handwriting recognition or text questions, a local Qwen2.5-VL model served via Ollama is integrated, enabling offline, highly secure processing of student answers. Teachers can upload multi-code key spreadsheets via Excel and process student submissions in bulk.",
    reflection:
      "Offline-first AI products require careful resource management. Tuning Qwen2.5-VL to run on consumer hardware showed me how to balance physical latency with inference accuracy, creating a private-by-design tool schools can trust.",
  },
  {
    slug: "fertilizer-classification",
    index: "03",
    title: "Fertilizer Classification",
    stack: "YOLOv8 · DeepSort · Python · OpenCV",
    year: "2023",
    role: "Computer Vision",
    description:
      "Real-time object detection and tracking for fertilizer classification on a moving production line — built and tuned for factory conditions.",
    highlight: "~92% accuracy · Encouragement Award, CTU",
    image: fertilizer,
    href: "https://youtube.com/shorts/3PrD-xn-jL0",
    github: "https://github.com/lpsangg/Ca-Mau-Fertilizer-Classification",
    context:
      "Developed for Petrovietnam Ca Mau Fertilizer Corporation (PVCFC) during an onsite internship, this system automates inventory management in agricultural supply chains. The goal was to build a computer vision pipeline capable of detecting, tracking, and classifying fertilizer bags on moving conveyor belts under challenging industrial conditions.",
    approach:
      "Trained a custom YOLOv8 model for high-speed object detection and classification. Integrated DeepSort for multi-object tracking to prevent double-counting as bags pass the camera sensor. The pipeline is written in Python using OpenCV for frame-by-frame processing and video ingestion, optimized to run with low latency on edge computing devices inside the manufacturing environment.",
    reflection:
      "Industrial AI is less about benchmark data and more about handling noise, dust, lighting changes, and camera vibration. Tuning YOLOv8 to achieve ~92% accuracy under variable physical conditions was a masterclass in robust dataset curation and real-time inference optimization.",
  },
  {
    slug: "oil-price-forecasting",
    index: "04",
    title: "Oil Price & Demand Forecasting",
    stack: "LSTM · TensorFlow · GitHub Actions · Docker",
    year: "2024",
    role: "MLOps · Time Series",
    description:
      "Time-series forecasting with LSTM, wrapped in a production-grade CI/CD pipeline so every model change ships through automated tests.",
    highlight: "95% test coverage",
    image: timeSeries,
    github: "https://github.com/lpsangg/Oil-Price-Forecasting-LSTM-API-Test",
    context:
      "Accurate demand forecasting is critical to optimizing inventory management and reducing stockout risks. This project implements a time-series forecasting model using LSTM networks to predict future demand and crude oil price trends, wrapped in a production-grade MLOps pipeline.",
    approach:
      "Built using TensorFlow/Keras for LSTM training and evaluation. Served the inference model via a RESTful FastAPI backend. The project highlights MLOps best practices with over 95% test coverage, comprehensive unit testing (for preprocessing, training, inference, and endpoints), and a fully automated CI/CD pipeline built with GitHub Actions that runs tests and packages the system inside Docker containers on every release.",
    reflection:
      "Shipping a model is only 10% of the work. Automating model testing, data drift checks, and containerized deployments taught me how to construct stable CI/CD pipelines that ensure machine learning models perform reliably in production.",
  },
  {
    slug: "speaker-recognition",
    index: "05",
    title: "Speaker Recognition",
    stack: "MFCC · LSTM · Python",
    year: "2023",
    role: "Audio · Deep Learning",
    description:
      "A voice identification system that learns speaker fingerprints from MFCC features and an LSTM network — biometric auth from a few seconds of audio.",
    image: speaker,
    github: "https://github.com/lpsangg/Speaker-Recognition-",
    context:
      "Biometric security requires lightweight, fast, and secure authentication. This project develops a voice biometrics system that extracts unique speaker fingerprints from raw audio recordings to perform real-time speaker identification.",
    approach:
      "Extracted Mel-Frequency Cepstral Coefficients (MFCC) from audio inputs to capture acoustic voice features. Trained an LSTM (Long Short-Term Memory) neural network in Python using PyTorch to learn sequence-based speaker signatures. Deployed the model using Flask, creating a simple web dashboard where users can record voice samples and perform biometric verification in seconds.",
    reflection:
      "Voice biometric signals are highly sensitive to background noise. Implementing robust audio preprocessing (noise gate, normalization) before feature extraction was key to achieving stable recognition accuracy from short voice clips.",
  },
];

function ProjectRow({ project, i }: { project: Project; i: number }) {
  const ref = useRef<HTMLDivElement>(null);
  const { scrollYProgress } = useScroll({ target: ref, offset: ["start end", "end start"] });
  const imgY = useTransform(scrollYProgress, [0, 1], [60, -60]);
  const imgScale = useTransform(scrollYProgress, [0, 0.5, 1], [1.12, 1, 1.06]);
  const overlayOpacity = useTransform(scrollYProgress, [0, 0.4, 0.6, 1], [0.5, 0, 0, 0.5]);

  return (
    <div ref={ref} className="border-t border-border/60 group/row">
      <div className="mx-auto max-w-7xl px-6 md:px-10 py-20 md:py-32 grid md:grid-cols-12 gap-10 md:gap-14 items-start">
        <div className={`md:col-span-5 md:sticky md:top-32 ${i % 2 === 1 ? "md:order-2" : ""}`}>
          <div className="flex items-center gap-4 text-xs text-muted-foreground tracking-wide uppercase mb-8">
            <span>{project.index}</span>
            <span className="h-px flex-1 bg-border group-hover/row:bg-foreground/30 transition-colors duration-500" />
            <span>{project.year}</span>
          </div>
          <MaskReveal
            text={project.title}
            className="font-serif text-5xl md:text-7xl tracking-tight leading-[0.95] mb-8 block"
          />
          <p className="text-base md:text-lg text-foreground/80 leading-relaxed max-w-md mb-8">
            {project.description}
          </p>
          {project.highlight && (
            <p className="inline-block text-xs uppercase tracking-wider bg-foreground text-background rounded-full px-3 py-1 mb-8">
              {project.highlight}
            </p>
          )}
          <dl className="grid grid-cols-[auto_1fr] gap-x-6 gap-y-3 text-sm max-w-md border-t border-border/60 pt-6">
            <dt className="text-muted-foreground">Stack</dt>
            <dd>{project.stack}</dd>
            <dt className="text-muted-foreground">Role</dt>
            <dd>{project.role}</dd>
            <dt className="text-muted-foreground">Year</dt>
            <dd>{project.year}</dd>
          </dl>
          {project.href && (
            <a
              href={project.href}
              target="_blank"
              rel="noreferrer noopener"
              data-cursor-text="DEMO"
              className="mt-8 inline-flex items-center gap-2 text-sm border-b border-foreground/40 pb-1 hover:border-foreground transition-colors group/cta"
            >
              Live demo
              <span className="inline-block transition-transform duration-500 group-hover/cta:translate-x-1">→</span>
            </a>
          )}
          <Link
            to="/work/$slug"
            params={{ slug: project.slug }}
            data-cursor-text="READ"
            className="mt-6 ml-0 md:ml-6 inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground transition-colors group/cs"
          >
            Read case study
            <span className="inline-block transition-transform duration-500 group-hover/cs:translate-x-1">→</span>
          </Link>
        </div>

        <div className={`md:col-span-7 ${i % 2 === 1 ? "md:order-1" : ""}`}>
          <motion.div
            initial={{ clipPath: "inset(0% 0% 100% 0%)" }}
            whileInView={{ clipPath: "inset(0% 0% 0% 0%)" }}
            viewport={{ once: true, margin: "-10%" }}
            transition={{ duration: 1.4, ease: EASE }}
            className="relative aspect-video overflow-hidden rounded-md bg-muted w-full group/img transition-all duration-700 ease-[cubic-bezier(0.22,1,0.36,1)] group-hover/row:scale-[1.012] group-hover/row:shadow-[0_12px_36px_-12px_rgba(0,0,0,0.08)] dark:group-hover/row:shadow-[0_12px_36px_-12px_rgba(255,255,255,0.015)]"
          >
            <Link
              to="/work/$slug"
              params={{ slug: project.slug }}
              data-cursor-text="VIEW"
              className="block absolute inset-0"
              aria-label={`Open ${project.title} case study`}
            >
              <motion.img
                src={project.image}
                alt={project.title}
                loading="lazy"
                style={{ y: imgY, scale: imgScale }}
                className="absolute inset-0 size-full object-contain bg-muted will-change-transform"
              />
              <motion.div
                style={{ opacity: overlayOpacity }}
                className="absolute inset-0 bg-foreground pointer-events-none"
              />
              <span className="absolute bottom-4 right-4 text-[10px] uppercase tracking-widest px-2.5 py-1 rounded-full bg-background/85 backdrop-blur border border-border text-foreground opacity-0 group-hover/img:opacity-100 transition-opacity">
                Case study ↗
              </span>
            </Link>
          </motion.div>
        </div>
      </div>
    </div>
  );
}

export function ProjectShowcase() {
  return (
    <section id="work" className="relative">
      <div className="mx-auto max-w-7xl px-6 md:px-10 pt-32 pb-12">
        <div className="flex items-end justify-between">
          <div>
            <p className="text-xs tracking-wide uppercase text-muted-foreground mb-4">Section / 03</p>
            <MaskReveal
              text="Selected work."
              className="font-serif text-5xl md:text-7xl tracking-tight leading-none block"
            />
          </div>
          <span className="text-sm text-muted-foreground">({String(projects.length).padStart(2, "0")})</span>
        </div>
      </div>
      {projects.map((p, i) => (
        <ProjectRow key={p.index} project={p} i={i} />
      ))}
    </section>
  );
}